### PR TITLE
Forum page

### PR DESCRIPTION
**Pull request by PGimenez**

### CODE REVIEW

**Comment by PGimenez** [comment]
you're a magician @ms10596 ! The export works and the format is perfect. I've added a build script to fetch the zipped json files from a link before building the site. For some reason it doesn't work on netlify, so I'll have to figure it out.

Another thing is that only the ~30 recent threads are exported. I've looked into the discorchatexporter docs but couldn't find an option to export older threads.

**Comment by ms10596** [comment]
Thanks, @PGimenez :heart:  Yeah, I couldn't export older threads. I guess we'll need to figure it out eventually.

**Comment by PGimenez** [comment]
> Thanks, @PGimenez ❤️ Yeah, I couldn't export older threads. I guess we'll need to figure it out eventually.

I've opened [an issue](https://github.com/Tyrrrz/DiscordChatExporter/issues/1129) on their repository. Let's see if a full export is possible, otherwise we can merge and work with the threads we have.

**Comment by PGimenez** [comment]
Even with `--include-threads all`not all threads are exported, but hopefully there'll be a solution for that soon. 

I'm merging now since the build script changes need to be propagated to other branches

**Pull request merged**
